#!/bin/bash

OSVERSION=`grep ^NAME /etc/os-release | awk -F= '{print $2}' | sed -e 's/"//g'`

if [[ "$OSVERSION" == "Ubuntu" ]]; then
  while fuser /var/lib/dpkg/lock >/dev/null 2>&1; do sleep 1; done
  apt-get install -y apache2
  /bin/rm -f /var/www/html/index.html
else
  yum install -y httpd
  /bin/rm -f /var/www/html/index.html
fi
