#!/bin/bash

OSVERSION=`grep ^NAME /etc/os-release | awk -F= '{print $2}' | sed -e 's/"//g'`
isExistApp=`pgrep httpd`

if [[ -n $isExistApp ]]; then
  if [[ "$OSVERSION" == "Ubuntu" ]]; then
    service apache2 stop
  else
    service httpd stop
  fi
fi

# Remove Old File
/bin/rm -f /var/www/html/index.html
